### ISSUE TITLE
support ansible openstack cloud files

### ISSUE THREAD

**Issue by joschkappel** [IBM/osslm-ansible-resource-manager#34]
current implementation only supports passing openstack auth properties as explicite parameters in the plays. 
To enhance reusability and limit dependency on vairous openstack auth options the resource manager should support cloud confg files.
Auth information is driven by os-client-config, which means that values can come from a yaml config file in /etc/ansible/openstack.yaml, /etc/openstack/clouds.yaml or ~/.config/openstack/clouds.yaml.

It is required as part of the CRUD for deployment location also manage the cloud config file.
With this play can simply use "cloud: cloud-name" to use any type fo auth scheme.

**Comment by paulnagleIBM** [comment]
Hi Jochen, just wondering if this is implemented? or still on the TODO list?

**Comment by joschkappel** [comment]
Hi Paul,
still an open issue
