### ISSUE TITLE
return code design

### ISSUE THREAD

**Issue by Gmikeit** [IBM/osslm-ansible-resource-manager#82]
Do you have any documentation on the return codes expected by an ansible playbook running on ansible rm and how those map to ALM assembly lifecycle status?

**Comment by joschkappel** [comment]
All failures in playbooks are appended to the initial ALM  transition request (requestStateReason, requestFailureCode).
Both properties are set depending on the cause of failure:

1. ansible task status: "unreachable":
requestStateReason = 'resource unreachable'
requestFailureCode = 'RESOURCE_NOT_FOUND'

2. ansible task status: "failed":
requestStateReason = 'resource tasks failed'

3. ansible task status: "ok" (these are application level errors raised by the playbook )
requestStateReason = failure_reason (must be set by playbook)
requestFailureCode = failure_code  (must be set by playbook)

Ansible playbooks can raise application level failures using this mechanism:
```yaml
    - name: report FAILURE
      debug:
         msg:
          - "failure_code: app_fcode"
          - "failure_reason: {{ app_reason  }}"
```
