### ISSUE TITLE
ansible-rm doesn't send topic creation requests to the controller.

### ISSUE THREAD

**Issue by eflamini** [IBM/osslm-ansible-resource-manager#84]
The request to create the ansible-rm topic fails with error code 41 (NO_CONTROLLER) which indicates the request is sent to a kafka broker that is not the controller.

I think the problem is related to the fact that the request is sent to a specific kafka broker: https://github.com/IBM/osslm-ansible-resource-manager/blob/8a5971909bbe613f4badeb50cd1680bdd375df4c/ansible-adaptor/swagger_server/controllers/ans_kafka_topic.py#L32)

While, this implementation works pointing to any of the cluster nodes on any of the exposed NodePorts:

```
from kafka.client_async import KafkaClient
from kafka.protocol import admin
from kafka.protocol.api import Response, Request
from kafka.protocol import types
from flask import current_app as app
from kafka.admin import KafkaAdminClient, NewTopic

def ensure_topic( topic, num_partitions, replication_factor,
                  timeout_ms=3000, brokers='localhost' ):
    adminclient = KafkaAdminClient(bootstrap_servers=brokers, client_id='eli_test')


    topic_list = []
    topic_list.append(NewTopic(name=topic, num_partitions=1, replication_factor=1))
    adminclient.create_topics(new_topics=topic_list, validate_only=False)

ensure_topic( topic='alm_test_eli4',num_partitions=1, replication_factor=1, brokers='<any_cluster_node>:<any_node_port>')
```

In the latter implementation, create_topics sends the request to the controller, as it can be seen in the create_topics implementation: https://kafka-python.readthedocs.io/en/master/_modules/kafka/admin/client.html.

**Comment by joschkappel** [comment]
Have changed code to use the kafka admin client. Fix has been comitted to master branch
