### ISSUE TITLE
Cannot start pod using Helm default values

### ISSUE THREAD

**Issue by karen-nguyen** [IBM/osslm-ansible-resource-manager#85]
Running `helm install https://github.com/IBM/osslm-ansible-resource-manager/releases/download/v1.3.6/osslm-ansible-resource-manager-1.3.6.tgz --name ansiblerm`
will leave osslm-ansible-rm pod in "Pending" state forever with message `persistentvolumeclaim "osslm-ansible-rm-vol4" not found`

If pod can not be started with persistence disabled, it should be enabled by default.

**Comment by beanallergy** [comment]
@joschkappel can you comment on this?
